# create your drupal and postgres config here, based off the last assignment
version: '2'


services:
  drupal:
    image: custom-drupal
    build: .
    ports:
      - 8080:80
      - 22
    networks:
      - sshtest
    extra_hosts:
      - github.blah.com:11.11.11.11
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypass
    ports:
      - 22
    networks:
      - sshtest
    extra_hosts:
      - github.blah.com:11.11.11.11
    volumes:
      - drupal-data:/var/lib/postgresql/data

networks:
    sshtest:
volumes:
    drupal-data:
    drupal-modules:
    drupal-profiles:
    drupal-sites:
    drupal-themes:
