FROM ubuntu:16.04
RUN apt-get update
# Pick up some TF dependencies
RUN apt-get install -y software-properties-common \
 curl \
 unzip \
 build-essential \
 libfreetype6-dev \
 libeigen3-dev \
 libgoogle-glog-dev \
 libleveldb-dev \
 liblmdb-dev \
 libopencv-dev \
 libprotobuf-dev \
 libsnappy-dev \
 zlib1g-dev \
 libbz2-dev \
 protobuf-compiler \
 libhdf5-serial-dev \
 libpng-dev \
 libzmq3-dev \
 pkg-config \
 vim \
 git \
 wget \
 python3-pip \
 pip3 install --upgrade pip \
 gfortran \
#graphviz \
 libatlas-base-dev

Dockerfile_pytorchOPENCV dependencies
# https://stackoverflow.com/questions/47113029/importerror-libsm-so-6-cannot-open-shared-object-file-no-such-file-or-directo
RUN apt-get install -y libsm6 libxext6
RUN apt-get install -y libfontconfig1 libxrender1

RUN mkdir /app
WORKDIR /app

RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh
RUN wget --quiet https://repo.anaconda.com/archive/Anaconda3-5.2.0-Linux-x86_64.sh -O ~/anaconda.sh
RUN /bin/bash ~/anaconda.sh -b -p /opt/conda
RUN rm ~/anaconda.sh

ENV PATH /opt/conda/bin:$PATH
RUN conda update conda && conda update anaconda && conda update --all
RUN conda install -y -c pytorch \
    pytorch-cpu=1.0.0 \
    torchvision-cpu=0.2.1 \
 && conda clean -ya

RUN conda install -y h5py=2.8.0 \
 && conda clean -ya
RUN conda install -y graphviz=2.38.0 \
  && conda clean -ya
RUN pip install graphviz==0.8.4
RUN pip install torchnet==0.0.4
RUN conda install -y requests=2.19.1 \
 && conda clean -ya
RUN pip install h5py-cache==1.0
#RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends \
  #  libgtk2.0-0 \
  #  libcanberra-gtk-module \
 #& sudo rm -rf /var/lib/apt/lists/*
RUN conda install -y -c menpo opencv3=3.1.0 \
 && conda clean -ya
#RUN pip3 install Pillow
#RUN pip3 install h5py
#RUN pip3 install ipykernel
#RUN pip3 install jupyter
#RUN pip3 install matplotlib
#Fix numpy to 1.13.3
#RUN pip3 install numpy==1.13.3
#RUN pip3 install pandas
#RUN pip3 install scipy
#RUN pip3 install sklearn
#RUN pip3 install pytorch
#RUN pip3 install keras
#RUN pip3 install opencv-python
#RUN pip3 install scikit-image
#RUN pip3 install tensorflow==1.7.0
#RUN python3 -m ipykernel.kernelspec

# For Jupyter notebook
EXPOSE 8888
#For TensorBoard
EXPOSE 6006

#WORKDIR ~/app

#Setup Tensorflow object detection
RUN git clone https://github.com/tensorflow/models.git

# RUN apt-get install -y protobuf-compiler
RUN pip3 install Cython
RUN pip3 install lxml

# https://github.com/tensorflow/models/issues/4002
# Installing Protobuf
RUN curl -OL https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
RUN unzip protoc-3.2.0-linux-x86_64.zip -d protoc3
RUN mv protoc3/bin/* /usr/local/bin/
RUN mv protoc3/include/* /usr/local/include/
RUN rm protoc-3.2.0-linux-x86_64.zip
RUN rm -rf protoc3

#RUN cd models/research
#RUN protoc ./models/research/object_detection/protos/*.proto --python_out=.
RUN cd models/research && protoc ./object_detection/protos/*.proto --python_out=.

# # From tensorflow/models/research/
RUN echo 'export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim' >> ~/.bashrc

RUN jupyter notebook --generate-config

COPY jupyter_notebook_config.py /root/.jupyter/jupyter_notebook_config.py

ENV PASSWORD Atinuke

CMD ["jupyter", "notebook", "--allow-root"]
